import * as Blockly from 'blockly'

export function registerBlocks() {
  Blockly.defineBlocksWithJsonArray([
    // ── CONTROL ──
    {
      type: 'wc_start',
      message0: '🚀 시작했을 때',
      nextStatement: null,
      colour: '#FFD23F',
      tooltip: '실행하기 버튼을 누르면 아래 블록을 실행합니다',
    },
    {
      type: 'wc_repeat',
      message0: '%1 번 반복하기',
      args0: [{ type: 'field_number', name: 'TIMES', value: 10, min: 1 }],
      message1: '%1',
      args1: [{ type: 'input_statement', name: 'DO' }],
      previousStatement: null,
      nextStatement: null,
      colour: '#FFD23F',
      tooltip: '블록을 N번 반복합니다',
    },
    {
      type: 'wc_forever',
      message0: '🔄 계속 반복하기',
      message1: '%1',
      args1: [{ type: 'input_statement', name: 'DO' }],
      previousStatement: null,
      colour: '#FFD23F',
      tooltip: '블록을 계속 반복합니다',
    },
    {
      type: 'wc_if',
      message0: '만약 %1 이라면',
      args0: [{ type: 'input_value', name: 'COND', check: 'Boolean' }],
      message1: '%1',
      args1: [{ type: 'input_statement', name: 'DO' }],
      previousStatement: null,
      nextStatement: null,
      colour: '#FFD23F',
      tooltip: '조건이 참이면 블록을 실행합니다',
    },
    {
      type: 'wc_wait',
      message0: '%1 초 기다리기',
      args0: [{ type: 'field_number', name: 'SECS', value: 1, min: 0.1, precision: 0.1 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#FFD23F',
      tooltip: 'N초 동안 기다립니다',
    },

    // ── MOTION ──
    {
      type: 'wc_move_steps',
      message0: '%1 만큼 이동하기',
      args0: [{ type: 'field_number', name: 'STEPS', value: 10 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#FF6B35',
      tooltip: '현재 방향으로 N만큼 이동합니다',
    },
    {
      type: 'wc_move_dir',
      message0: '%1 으로 %2 이동',
      args0: [
        {
          type: 'field_dropdown',
          name: 'DIR',
          options: [
            ['위쪽', 'UP'],
            ['아래쪽', 'DOWN'],
            ['오른쪽', 'RIGHT'],
            ['왼쪽', 'LEFT'],
          ],
        },
        { type: 'field_number', name: 'STEPS', value: 10, min: 1 },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: '#FF6B35',
      tooltip: '방향으로 N만큼 이동합니다',
    },
    {
      type: 'wc_go_to',
      message0: 'x: %1 y: %2 로 이동',
      args0: [
        { type: 'field_number', name: 'X', value: 0 },
        { type: 'field_number', name: 'Y', value: 0 },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: '#FF6B35',
      tooltip: '지정한 좌표로 이동합니다',
    },
    {
      type: 'wc_rotate',
      message0: '%1 도 회전하기',
      args0: [{ type: 'field_number', name: 'DEGREES', value: 15 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#FF6B35',
      tooltip: 'N도 회전합니다',
    },
    {
      type: 'wc_reset_pos',
      message0: '처음 위치로 가기',
      previousStatement: null,
      nextStatement: null,
      colour: '#FF6B35',
      tooltip: '스프라이트를 처음 위치(0,0)로 이동합니다',
    },

    // ── SENSING ──
    {
      type: 'wc_key_hat_up',
      message0: '↑ 위 키 눌렸을 때',
      nextStatement: null,
      colour: '#2EC4B6',
      tooltip: '위쪽 화살표 키를 누르면 아래 블록을 실행합니다',
    },
    {
      type: 'wc_key_hat_down',
      message0: '↓ 아래 키 눌렸을 때',
      nextStatement: null,
      colour: '#2EC4B6',
      tooltip: '아래쪽 화살표 키를 누르면 아래 블록을 실행합니다',
    },
    {
      type: 'wc_key_hat_left',
      message0: '← 왼쪽 키 눌렸을 때',
      nextStatement: null,
      colour: '#2EC4B6',
      tooltip: '왼쪽 화살표 키를 누르면 아래 블록을 실행합니다',
    },
    {
      type: 'wc_key_hat_right',
      message0: '→ 오른쪽 키 눌렸을 때',
      nextStatement: null,
      colour: '#2EC4B6',
      tooltip: '오른쪽 화살표 키를 누르면 아래 블록을 실행합니다',
    },
    {
      type: 'wc_key_hat_space',
      message0: '스페이스 눌렸을 때',
      nextStatement: null,
      colour: '#2EC4B6',
      tooltip: '스페이스 키를 누르면 아래 블록을 실행합니다',
    },
    {
      type: 'wc_wall_touching',
      message0: '벽에 닿았을 때',
      output: 'Boolean',
      colour: '#2EC4B6',
      tooltip: '스프라이트가 벽에 닿으면 참을 반환합니다',
    },
    {
      type: 'wc_mouse_click_hat',
      message0: '마우스를 클릭했을 때',
      nextStatement: null,
      colour: '#2EC4B6',
      tooltip: '마우스를 클릭하면 아래 블록을 실행합니다',
    },

    // ── SPEECH ──
    {
      type: 'wc_say',
      message0: '💬 %1 이라고 말하기',
      args0: [{ type: 'field_input', name: 'TEXT', text: '안녕!' }],
      previousStatement: null,
      nextStatement: null,
      colour: '#FF85A1',
      tooltip: '말풍선을 표시합니다',
    },
    {
      type: 'wc_say_for',
      message0: '💬 %1 을(를) %2 초 동안 말하기',
      args0: [
        { type: 'field_input', name: 'TEXT', text: '안녕!' },
        { type: 'field_number', name: 'SECS', value: 2, min: 0.1, precision: 0.1 },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: '#FF85A1',
      tooltip: 'N초 동안 말풍선을 표시합니다',
    },
    {
      type: 'wc_clear_speech',
      message0: '말풍선 지우기',
      previousStatement: null,
      nextStatement: null,
      colour: '#FF85A1',
      tooltip: '말풍선을 지웁니다',
    },

    // ── LOOKS ──
    {
      type: 'wc_show',
      message0: '보이기',
      previousStatement: null,
      nextStatement: null,
      colour: '#A855F7',
      tooltip: '스프라이트를 보이게 합니다',
    },
    {
      type: 'wc_hide',
      message0: '숨기기',
      previousStatement: null,
      nextStatement: null,
      colour: '#A855F7',
      tooltip: '스프라이트를 숨깁니다',
    },
    {
      type: 'wc_set_size',
      message0: '크기를 %1 % 로 설정',
      args0: [{ type: 'field_number', name: 'SIZE', value: 100, min: 10, max: 400 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#A855F7',
      tooltip: '스프라이트 크기를 설정합니다',
    },
    {
      type: 'wc_change_size',
      message0: '크기를 %1 키우기',
      args0: [{ type: 'field_number', name: 'DELTA', value: 10 }],
      previousStatement: null,
      nextStatement: null,
      colour: '#A855F7',
      tooltip: '스프라이트 크기를 변경합니다',
    },

    // ── SOUND (stub) ──
    {
      type: 'wc_play_sound',
      message0: '🎵 소리 재생하기',
      previousStatement: null,
      nextStatement: null,
      colour: '#3B82F6',
      tooltip: '소리를 재생합니다 (준비 중)',
    },
    {
      type: 'wc_stop_sound',
      message0: '소리 멈추기',
      previousStatement: null,
      nextStatement: null,
      colour: '#3B82F6',
      tooltip: '소리를 멈춥니다 (준비 중)',
    },
  ])
}

export const TOOLBOX_CONFIG = {
  kind: 'categoryToolbox',
  contents: [
    {
      kind: 'category',
      name: '🔄 제어',
      colour: '#FFD23F',
      contents: [
        { kind: 'block', type: 'wc_start' },
        { kind: 'block', type: 'wc_repeat' },
        { kind: 'block', type: 'wc_forever' },
        { kind: 'block', type: 'wc_if' },
        { kind: 'block', type: 'wc_wait' },
      ],
    },
    {
      kind: 'category',
      name: '🏃 움직임',
      colour: '#FF6B35',
      contents: [
        { kind: 'block', type: 'wc_move_steps' },
        { kind: 'block', type: 'wc_move_dir' },
        { kind: 'block', type: 'wc_go_to' },
        { kind: 'block', type: 'wc_rotate' },
        { kind: 'block', type: 'wc_reset_pos' },
      ],
    },
    {
      kind: 'category',
      name: '👀 감지',
      colour: '#2EC4B6',
      contents: [
        { kind: 'block', type: 'wc_key_hat_up' },
        { kind: 'block', type: 'wc_key_hat_down' },
        { kind: 'block', type: 'wc_key_hat_left' },
        { kind: 'block', type: 'wc_key_hat_right' },
        { kind: 'block', type: 'wc_key_hat_space' },
        { kind: 'block', type: 'wc_wall_touching' },
        { kind: 'block', type: 'wc_mouse_click_hat' },
      ],
    },
    {
      kind: 'category',
      name: '💬 말풍선',
      colour: '#FF85A1',
      contents: [
        { kind: 'block', type: 'wc_say' },
        { kind: 'block', type: 'wc_say_for' },
        { kind: 'block', type: 'wc_clear_speech' },
      ],
    },
    {
      kind: 'category',
      name: '✨ 모양',
      colour: '#A855F7',
      contents: [
        { kind: 'block', type: 'wc_show' },
        { kind: 'block', type: 'wc_hide' },
        { kind: 'block', type: 'wc_set_size' },
        { kind: 'block', type: 'wc_change_size' },
      ],
    },
    {
      kind: 'category',
      name: '🎵 소리',
      colour: '#3B82F6',
      contents: [
        { kind: 'block', type: 'wc_play_sound' },
        { kind: 'block', type: 'wc_stop_sound' },
      ],
    },
  ],
}
